/**
 * Debug script to check reports and lecturer assignments
 */

require('dotenv').config();
const prisma = require('./src/lib/prisma');

async function debugReports() {
  console.log('🔍 Debugging Reports and Lecturer Assignments\n');

  try {
    // 1. Check all reports
    console.log('=== ALL OFFICIAL REPORTS ===');
    const allReports = await prisma.officialReport.findMany({
      include: {
        class: { include: { programme: true } },
        course: true,
        generatedBy: { select: { username: true, role: true } }
      },
      orderBy: { createdAt: 'desc' },
      take: 10
    });

    console.log(`Total reports: ${allReports.length}\n`);
    allReports.forEach(r => {
      console.log(`Report ID: ${r.id}`);
      console.log(`  Status: ${r.status}`);
      console.log(`  Class: ${r.class.displayName} (ID: ${r.classId})`);
      console.log(`  Course: ${r.course.name} (${r.course.code}) (ID: ${r.courseId})`);
      console.log(`  Generated by: ${r.generatedBy.username} (${r.generatedBy.role})`);
      console.log(`  Created: ${r.createdAt}`);
      console.log('');
    });

    // 2. Check pending reports
    console.log('\n=== PENDING REPORTS (PENDING_SIGNATURE) ===');
    const pendingReports = await prisma.officialReport.findMany({
      where: { status: 'PENDING_SIGNATURE' },
      include: {
        class: true,
        course: true
      }
    });

    console.log(`Pending reports count: ${pendingReports.length}\n`);
    pendingReports.forEach(r => {
      console.log(`Report ID: ${r.id}`);
      console.log(`  Class ID: ${r.classId}`);
      console.log(`  Course ID: ${r.courseId}`);
      console.log('');
    });

    // 3. Check all lecturers
    console.log('\n=== ALL LECTURERS ===');
    const lecturers = await prisma.user.findMany({
      where: { role: 'LECTURER' },
      select: {
        id: true,
        username: true,
        isActive: true
      }
    });

    console.log(`Total lecturers: ${lecturers.length}\n`);
    lecturers.forEach(l => {
      console.log(`Lecturer: ${l.username} (ID: ${l.id}, Active: ${l.isActive})`);
    });

    // 4. Check lecturer assignments
    console.log('\n=== LECTURER ASSIGNMENTS ===');
    const assignments = await prisma.lecturerAssignment.findMany({
      include: {
        lecturer: { select: { username: true } },
        class: { include: { programme: true } },
        course: true
      }
    });

    console.log(`Total assignments: ${assignments.length}\n`);
    assignments.forEach(a => {
      console.log(`Lecturer: ${a.lecturer.username}`);
      console.log(`  Class: ${a.class.displayName} (ID: ${a.classId})`);
      console.log(`  Course: ${a.course.name} (${a.course.code}) (ID: ${a.courseId})`);
      console.log('');
    });

    // 5. Match pending reports with lecturer assignments
    console.log('\n=== MATCHING PENDING REPORTS WITH LECTURERS ===');
    if (pendingReports.length === 0) {
      console.log('No pending reports to match.');
    } else {
      for (const report of pendingReports) {
        console.log(`\nReport ID: ${report.id}`);
        console.log(`  Class ID: ${report.classId}`);
        console.log(`  Course ID: ${report.courseId}`);
        
        const matchingAssignments = assignments.filter(
          a => a.classId === report.classId && a.courseId === report.courseId
        );

        if (matchingAssignments.length > 0) {
          console.log(`  ✅ Matched with ${matchingAssignments.length} lecturer(s):`);
          matchingAssignments.forEach(a => {
            console.log(`     - ${a.lecturer.username}`);
          });
        } else {
          console.log(`  ❌ NO MATCHING LECTURER ASSIGNMENT!`);
          console.log(`     This report won't show up for any lecturer.`);
        }
      }
    }

    console.log('\n✅ Debug complete!\n');

  } catch (error) {
    console.error('❌ Error:', error);
  } finally {
    await prisma.$disconnect();
  }
}

debugReports();
