import { useState, useEffect } from 'react';
import api from '../../services/api';

export default function OfficialArchives() {
  const [groupedReports, setGroupedReports] = useState({});
  const [loading, setLoading] = useState(true);
  const [expandedLevels, setExpandedLevels] = useState({});

  useEffect(() => {
    fetchArchives();
  }, []);

  const fetchArchives = async () => {
    try {
      const res = await api.get('/reports/archived');
      setGroupedReports(res.data);
      // Expand first level by default
      const firstKey = Object.keys(res.data)[0];
      if (firstKey) {
        setExpandedLevels({ [firstKey]: true });
      }
    } catch (err) {
      console.error('Failed to fetch archives', err);
    } finally {
      setLoading(false);
    }
  };

  const toggleLevel = (level) => {
    setExpandedLevels(prev => ({ ...prev, [level]: !prev[level] }));
  };

  if (loading) {
    return <div className="text-slate-400 text-center py-10">Loading archives...</div>;
  }

  if (Object.keys(groupedReports).length === 0) {
    return (
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-10 text-center">
        <h3 className="text-xl font-bold text-white mb-2">No Reports Archived Yet</h3>
        <p className="text-slate-400">Archived reports will appear here once generated by reps and signed by lecturers.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-black text-white tracking-tight">Official Archives</h2>
          <p className="text-sm text-slate-400">Digitally signed course attendance reports.</p>
        </div>
      </div>

      <div className="space-y-4">
        {Object.entries(groupedReports).map(([level, groups]) => {
          // Count total reports in this level
          const totalReports = Object.values(groups).reduce((sum, reports) => sum + reports.length, 0);
          
          return (
          <div key={level} className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden">
            <button 
              onClick={() => toggleLevel(level)}
              className="w-full flex items-center justify-between p-5 bg-slate-800/50 hover:bg-slate-800 transition"
            >
              <div className="flex items-center gap-3">
                <svg className="w-6 h-6 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
                </svg>
                <h3 className="text-lg font-bold text-white">Level {level}</h3>
                <span className="text-xs bg-slate-700 text-slate-300 px-2 py-0.5 rounded-full font-mono">
                  {totalReports} report{totalReports !== 1 ? 's' : ''}
                </span>
              </div>
              <svg className={`w-5 h-5 text-slate-400 transition-transform ${expandedLevels[level] ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>

            {expandedLevels[level] && (
              <div className="p-5 divide-y divide-slate-800/50 space-y-4">
                {Object.entries(groups).map(([group, reports]) => (
                  <div key={group} className="pt-4 first:pt-0 pl-4 border-l-2 border-indigo-500/20 ml-3">
                    <h4 className="text-md font-bold text-indigo-300 mb-3 flex items-center gap-2">
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                      </svg>
                      Group {group}
                    </h4>
                    <div className="grid gap-3 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
                      {reports.map(report => (
                        <div key={report.id} className="bg-[#0f172a] border border-slate-700 rounded-xl p-4 flex flex-col justify-between">
                          <div>
                            <div className="flex justify-between items-start mb-2">
                              <span className="text-xs font-bold px-2 py-1 bg-indigo-500/10 text-indigo-400 rounded-lg">
                                {report.course.code}
                              </span>
                              <span className="text-[10px] text-slate-500">
                                {new Date(report.signedAt).toLocaleDateString()}
                              </span>
                            </div>
                            <h5 className="text-white font-medium text-sm line-clamp-1">{report.course.name}</h5>
                            <p className="text-xs text-slate-400 mt-1">Signed by: {report.signedBy?.username}</p>
                          </div>
                          
                          <a 
                            href={report.fileUrl}
                            download
                            className="mt-4 flex items-center justify-center gap-2 w-full py-2 bg-emerald-600/10 hover:bg-emerald-600/20 text-emerald-400 text-xs font-bold rounded-lg transition"
                          >
                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                            </svg>
                            Download Report
                          </a>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
          );
        })}
      </div>
    </div>
  );
}
