import { useState, useEffect } from 'react';
import api from '../../services/api';

export default function OfficialArchives() {
  const [groupedReports, setGroupedReports] = useState({});
  const [loading, setLoading] = useState(true);
  const [expandedProgrammes, setExpandedProgrammes] = useState({});
  const [expandedLevels, setExpandedLevels] = useState({});
  const [searchQuery, setSearchQuery] = useState('');
  const [filterProgramme, setFilterProgramme] = useState('');
  const [filterLevel, setFilterLevel] = useState('');

  const fetchArchives = async () => {
    try {
      const res = await api.get('/reports/archived');
      setGroupedReports(res.data);
      // Expand first programme by default
      const firstKey = Object.keys(res.data)[0];
      if (firstKey) {
        setExpandedProgrammes({ [firstKey]: true });
      }
    } catch (err) {
      console.error('Failed to fetch archives', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchArchives();
  }, []);

  const toggleProgramme = (programme) => {
    setExpandedProgrammes(prev => ({ ...prev, [programme]: !prev[programme] }));
  };

  const toggleLevel = (programmeLevel) => {
    setExpandedLevels(prev => ({ ...prev, [programmeLevel]: !prev[programmeLevel] }));
  };

  // Count total reports in a programme
  const countProgrammeReports = (levels) => {
    return Object.values(levels).reduce((sum, groups) => {
      return sum + Object.values(groups).reduce((gSum, reports) => gSum + reports.length, 0);
    }, 0);
  };

  // Count total reports in a level
  const countLevelReports = (groups) => {
    return Object.values(groups).reduce((sum, reports) => sum + reports.length, 0);
  };

  // Filter reports based on search and filters
  const getFilteredReports = () => {
    let filtered = { ...groupedReports };

    // Filter by programme
    if (filterProgramme) {
      filtered = { [filterProgramme]: filtered[filterProgramme] };
    }

    // Filter by level
    if (filterLevel) {
      filtered = Object.fromEntries(
        Object.entries(filtered).map(([prog, levels]) => [
          prog,
          { [filterLevel]: levels[filterLevel] }
        ]).filter(([, levels]) => Object.keys(levels).length > 0)
      );
    }

    // Filter by search query (course name or code)
    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      filtered = Object.fromEntries(
        Object.entries(filtered).map(([prog, levels]) => [
          prog,
          Object.fromEntries(
            Object.entries(levels).map(([level, groups]) => [
              level,
              Object.fromEntries(
                Object.entries(groups).map(([group, reports]) => [
                  group,
                  reports.filter(r =>
                    r.course.name.toLowerCase().includes(query) ||
                    r.course.code.toLowerCase().includes(query)
                  )
                ]).filter(([, reports]) => reports.length > 0)
              )
            ]).filter(([, groups]) => Object.keys(groups).length > 0)
          )
        ]).filter(([, levels]) => Object.keys(levels).length > 0)
      );
    }

    return filtered;
  };

  const filteredReports = getFilteredReports();
  const programmes = Object.keys(groupedReports);
  const allLevels = [...new Set(Object.values(groupedReports).flatMap(levels => Object.keys(levels)))].sort();

  if (loading) {
    return <div className="text-slate-400 text-center py-10">Loading archives...</div>;
  }

  if (Object.keys(groupedReports).length === 0) {
    return (
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-10 text-center">
        <div className="flex justify-center mb-4">
          <svg className="w-16 h-16 text-slate-700" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
          </svg>
        </div>
        <h3 className="text-xl font-bold text-white mb-2">No Reports Archived Yet</h3>
        <p className="text-slate-400">Archived reports will appear here once generated by reps and signed by lecturers.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-start mb-6">
        <div>
          <h2 className="text-2xl font-black text-white tracking-tight">📊 Official Archives</h2>
          <p className="text-sm text-slate-400 mt-1">Digitally signed course attendance reports organized by programme and level.</p>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1.5">Search Reports</label>
            <input
              type="text"
              placeholder="Course name or code..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-[#0f172a] border border-slate-800 rounded-xl px-4 py-2 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1.5">Programme</label>
            <select
              value={filterProgramme}
              onChange={(e) => setFilterProgramme(e.target.value)}
              className="w-full bg-[#0f172a] border border-slate-800 rounded-xl px-4 py-2 text-sm text-white focus:outline-none focus:border-indigo-500"
            >
              <option value="">All Programmes</option>
              {programmes.map(prog => (
                <option key={prog} value={prog}>{prog}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-xs font-semibold text-slate-400 mb-1.5">Level</label>
            <select
              value={filterLevel}
              onChange={(e) => setFilterLevel(e.target.value)}
              className="w-full bg-[#0f172a] border border-slate-800 rounded-xl px-4 py-2 text-sm text-white focus:outline-none focus:border-indigo-500"
            >
              <option value="">All Levels</option>
              {allLevels.map(level => (
                <option key={level} value={level}>Level {level}</option>
              ))}
            </select>
          </div>
          <div className="flex items-end">
            <button
              onClick={() => {
                setSearchQuery('');
                setFilterProgramme('');
                setFilterLevel('');
              }}
              className="w-full bg-slate-800 hover:bg-slate-700 text-white text-sm font-semibold px-4 py-2 rounded-xl transition"
            >
              Clear Filters
            </button>
          </div>
        </div>
      </div>

      {/* Hierarchical View */}
      <div className="space-y-4">
        {Object.entries(filteredReports).map(([programmeName, levels]) => {
          const totalProgrammeReports = countProgrammeReports(levels);
          const programmeKey = programmeName;

          return (
            <div key={programmeName} className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden">
              {/* Programme Level */}
              <button
                onClick={() => toggleProgramme(programmeKey)}
                className="w-full flex items-center justify-between p-5 bg-gradient-to-r from-indigo-900/20 to-slate-900 hover:from-indigo-900/30 hover:to-slate-800 transition"
              >
                <div className="flex items-center gap-3">
                  <svg className="w-7 h-7 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
                  </svg>
                  <div className="text-left">
                    <h3 className="text-lg font-bold text-white">{programmeName}</h3>
                    <p className="text-xs text-slate-400">Programme</p>
                  </div>
                  <span className="text-xs bg-indigo-500/20 text-indigo-300 px-3 py-1 rounded-full font-bold">
                    {totalProgrammeReports} report{totalProgrammeReports !== 1 ? 's' : ''}
                  </span>
                </div>
                <svg
                  className={`w-5 h-5 text-slate-400 transition-transform ${expandedProgrammes[programmeKey] ? 'rotate-180' : ''}`}
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              </button>

              {/* Levels */}
              {expandedProgrammes[programmeKey] && (
                <div className="p-5 space-y-4">
                  {Object.entries(levels).map(([level, groups]) => {
                    const totalLevelReports = countLevelReports(groups);
                    const levelKey = `${programmeKey}-${level}`;

                    return (
                      <div key={level} className="bg-[#0f172a] border border-slate-800 rounded-xl overflow-hidden">
                        {/* Level Header */}
                        <button
                          onClick={() => toggleLevel(levelKey)}
                          className="w-full flex items-center justify-between p-4 bg-slate-800/30 hover:bg-slate-800/50 transition"
                        >
                          <div className="flex items-center gap-3">
                            <svg className="w-5 h-5 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                            </svg>
                            <h4 className="text-md font-bold text-white">Level {level}</h4>
                            <span className="text-xs bg-slate-700 text-slate-300 px-2 py-0.5 rounded-full font-mono">
                              {totalLevelReports} report{totalLevelReports !== 1 ? 's' : ''}
                            </span>
                          </div>
                          <svg
                            className={`w-4 h-4 text-slate-400 transition-transform ${expandedLevels[levelKey] ? 'rotate-180' : ''}`}
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                          >
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </button>

                        {/* Groups */}
                        {expandedLevels[levelKey] && (
                          <div className="p-4 space-y-4">
                            {Object.entries(groups).map(([groupKey, reports]) => (
                              <div key={groupKey} className="pl-4 border-l-2 border-indigo-500/30">
                                <h5 className="text-sm font-bold text-indigo-300 mb-3 flex items-center gap-2">
                                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                                  </svg>
                                  Group {groupKey}
                                  <span className="text-xs text-slate-500 font-normal">({reports.length} report{reports.length !== 1 ? 's' : ''})</span>
                                </h5>
                                <div className="grid gap-3 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
                                  {reports.map(report => (
                                    <div key={report.id} className="bg-slate-900 border border-slate-700 rounded-xl p-4 flex flex-col justify-between hover:border-indigo-500/50 transition">
                                      <div>
                                        <div className="flex justify-between items-start mb-2">
                                          <span className="text-xs font-bold px-2 py-1 bg-indigo-500/10 text-indigo-400 rounded-lg">
                                            {report.course.code}
                                          </span>
                                          <span className="text-[10px] text-slate-500">
                                            {new Date(report.signedAt).toLocaleDateString()}
                                          </span>
                                        </div>
                                        <h6 className="text-white font-medium text-sm line-clamp-2 mb-1">{report.course.name}</h6>
                                        <p className="text-xs text-slate-400">Signed by: {report.signedBy?.username}</p>
                                      </div>

                                      <a
                                        href={report.fileUrl}
                                        download
                                        className="mt-4 flex items-center justify-center gap-2 w-full py-2 bg-emerald-600/10 hover:bg-emerald-600/20 text-emerald-400 text-xs font-bold rounded-lg transition"
                                      >
                                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                        </svg>
                                        Download Report
                                      </a>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Empty State for Filtered Results */}
      {Object.keys(filteredReports).length === 0 && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-10 text-center">
          <svg className="w-16 h-16 text-slate-700 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <h3 className="text-lg font-bold text-white mb-2">No Reports Found</h3>
          <p className="text-slate-400 text-sm">Try adjusting your filters or search query.</p>
        </div>
      )}
    </div>
  );
}
